version: "3.8"

services:
  nginx:
    build: ./nginx
    container_name: cleaning_website_nginx_cont
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - cleaning-website
    restart: always

  mongo:
    image: mongo:6
    container_name: cleaning-website-mongo
    environment:
      MONGO_INITDB_DATABASE: cleaning-website-mongo
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    networks:
      - cleaning-website
    volumes:
      - cleaning-website-mongo:/data/db
    restart: always
    healthcheck:
      test: ["CMD", "mongosh", "-u", "admin", "-p", "123456", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s


  backend:
    build: ./server
    container_name: cleaning_website_backend
    ports:
      - "5002:5002"
    env_file: ./server/.env
    networks:
      - cleaning-website
    volumes:
      - uploads_data:/app/uploads
    depends_on:
        mongo:
         condition: service_healthy
    restart: always

  frontend:
    build:
      context: ./client
    container_name: cleaning_website_frontend
    ports:
      - "5175:5175"
    networks:
      - cleaning-website
    env_file: ./client/.env
    depends_on:
      - backend
    restart: always

networks:
  cleaning-website:
    driver: bridge

volumes:
  uploads_data:
  cleaning-website-mongo: